### ISSUE TITLE
[Setup Support] Including a tutorial for standing up own instance of Perseus using Docker

### ISSUE THREAD

**Issue by ssamus** [OHDSI/Perseus#12] opened 2022-10-20 09:36 UTC

**Comment by ssamus** [comment] 2022-10-20 09:47
Hi @Zwky26 We have instructions on GitHub https://github.com/OHDSI/Perseus#starting-with-docker-compose Could you please explain what you expect the results to be?

**Comment by Zwky26** [comment] 2022-10-21 14:23
Further user feedback specified that the issue is related to errors of current Docker compose code, not on lack of documentation. This issue is duplicate of #7, so this issue can be closed.

**Comment by ssamus** [comment] 2022-10-24 08:54
Duplicate

**Closed** 2022-10-24 08:54 UTC
Labels: documentation
